# Generated by Django 4.2.3 on 2023-07-05 14:41

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
