# Generated by Django 4.2.3 on 2023-07-05 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0003_alter_blogmodel_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='Blog',
        ),
    ]
