# Generated by Django 4.2.3 on 2023-07-15 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0004_rename_blogmodel_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
