# Generated by Django 4.2.3 on 2023-08-03 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0005_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bookmarks',
            field=models.ManyToManyField(default=None, related_name='bookmarked_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
